version: '3.8'
services:
  bank_api:
    build: .
    restart: always
    environment:
      -  PORT=8000
    ports:
      - '8000:8000'
    
#   db:
#     image: postgres:14.1-alpine
#     restart: always
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#     ports:
#       - '8001:5432'
#     volumes: 
#       - db:/var/lib/postgresql/data
# volumes:
#   db:
#     driver: local